### PR TITLE
Collaboration list

### PR DESCRIPTION
**Pull request by cherylepatrick**
This is a first draught of the collaboration list. It isn't finished but I would like to see what people think. I use jekyll data to load a list of people from a CSV file, seeded with the mailing list subscriptions table. That only included names and email addresses - I have added columns for photo, job title, interests (e.g. physics coordinator or whatever) as well as flags for whether people are OK with having their email displayed, and for whether they are active collaborators (not done anything with this yet - would like suggestions). I use the domain name of the email address to get details of the institution. Clicking pops up a "business card" with the person's details and photo. If they have no photo, they get the institution's logo; if that's unknown (e.g. they are using a gmail address), they get the SuperNEMO logo. The list is too long and I would like suggestions for pruning (remove or separate out inactive members) or organising it (by institution? by seniority e.g. academics/postdocs/students). Ideas please!

### CODE REVIEW

**Comment by drbenmorgan** [comment]
@cherylepatrick Could you review the build errors please (click on the "Details" link next to "The Travis CI build failed")?

These can also be run locally using `./snjekyll build && ./snjekyll test`. Most are timeouts, but there are a few others.

**Comment by cherylepatrick** [comment]
@drbenmorgan That's fine, I will go through these.
`./snjekyll test` doesn't work for me, is there any other way I can rerun the tests so I can check if I've fixed the problems without having to bother you?
Output of `./snjekyll test`:
Cheryls-MBP:SuperNEMO-DBD.github.io cpatrick$ ./snjekyll test
./snjekyll:70: "[snjekyll]: Homebrew install of `xz` detected: You may see errors in the install of the `nokogiri` gem. If so, do `brew unlink xz` and try again. You can relink the `xz` formulae after Jekyll installation is complete."
make: *** No rule to make target `test'.  Stop.

**Comment by drbenmorgan** [comment]
@cherylepatrick The branch looks to have the commits that added the `test` target, could you check the `snjekyll` you're using has the `test` target in its contents?

For reference, the command the test is running is (assuming it's run from the same directory as `snjekyll`:

```
$ GEM_HOME=$(pwd)/.gem PATH=$(pwd)/.gem/bin:$PATH bundle exec htmlproofer --log-level debug --url-ignore "Falaise" ./_site

**Comment by cherylepatrick** [comment]
Sorry, been neglecting this for a bit. The snjekyll script does include test and it is starting to run now, but I'm getting an error: 

```
Cheryls-MBP:SuperNEMO-DBD.github.io cpatrick$ GEM_HOME=$(pwd)/.gem PATH=$(pwd)/.gem/bin:$PATH bundle exec htmlproofer --log-level debug --url-ignore "Falaise" ./_site
Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ["./_site"] on *.html... 

Checking imagecheck on ./_site/about.html ...
Checking linkcheck on ./_site/about.html ...
Checking scriptcheck on ./_site/about.html ...
htmlproofer 3.6.0 | Error:  invalid byte sequence in UTF-8
```
Any ideas?

**Comment by cherylepatrick** [comment]
OK well, somewhere in all these files there is apparently an invalid byte sequence. If anyone has some idea how I can track that down, can they tell me? A lot of people have accents in their names, could it be that? Do I need to tell it to use UTF8 encoding somehow?

**Comment by cherylepatrick** [comment]
I ran the test on every individual html page and they all passed, so I don't really understand what it's complaining about. The errors in the original pull request are fixed, at least. So I don't really know what else I can do now. @drbenmorgan I don't know if you have any other ideas? Can we just merge it with that mystery error?

**Comment by drbenmorgan** [comment]
@cherylepatrick I *think* I saw an issue like this before, but can't find it in the commits right now. Let me checkout the PR locally and see if I can reproduce. It's quite possibly a Travis issue rather than anything in the html.

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan - everything is always trouble, isn't it?

**Comment by drbenmorgan** [comment]
@cherylepatrick I _think_ I've tracked this down - inside `assets/institution_logos` there is an "index.html" file, but this is *not* html but PNG! HTMLProofer only goes via file extension, so checks it an of course barfs.

I don't know what that file is as I couldn't find an obvious link to it in the code. I guess rename it or remove as needed. That should fix the UTF-8 issue, but you may find some more with collaboration links.

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan - I think you are right, the test runs now. That file got made by some program I was attempting to use to download all the images linked from the page so I could keep local copies. (I never got it to work and ended up writing my own python script to grab 'em.) Deleted it and now it is ok.

**Comment by cherylepatrick** [comment]
Now it is whining about a broken link but I don't know why, the link is fine.

**Comment by drbenmorgan** [comment]
I've rerun the build and checked the links - I don't know why the UCL and Stuba links fail, though trying them locally in the browser there is a noticeable delay in connecting the latter. I'd guess the UCL one is just something to do with local certificates on the Travis machine.

As the links work fine interactively, I'll merge.

**Pull request merged**
