### PR TITLE
Master

### PR DESCRIPTION
**Pull request by cherylepatrick**
All published nemo3/supernemo papers are on the list - should we add
things like talks and posters? What about “media” like picture gallery,
youtube channel etc?

### CODE REVIEW

**Comment by drbenmorgan** [comment]
@cherylepatrick, I think adding placeholders for these would be good. There're already a lot of changes in this PR, so I think we should get the basics in place, merge, and then have smaller PRs for each extra bit of content. Does that should reasonable?

**Comment by cherylepatrick** [comment]
@drbenmorgan YES, conceptually that sounds extremely sensible and I am totally up for it if I can figure out how to do it. Problem for me is that I'm pretty new to using git and not very elegant at managing it (basically I am just shoving everything I do in one master branch because that seemed easy). I didn't really intentionally merge everything into one pull request... I just clicked the button in GitHub desktop and it magically did that for me. Any suggestions on how to manage it in a more organised way would be very welcome!

**Comment by drbenmorgan** [comment]
@cherylepatrick What's worked reasonably well for me is the "feature branch" workflow described here:

https://www.atlassian.com/git/tutorials/comparing-workflows#feature-branch-workflow

This keeps work on orthogonal tasks nicely isolated in their own branches so they don't interfere.
It's more important that the PR implements a single "thing", e.g. one PR for "Implement A", one for "Fix Bug 1" rather than "Implement A and Fix Bug1" rather than the exact branch used. Separate branches just help to prevent these lines interfering - and certainly branches are much easier to use and manage in Git compared with SVN!

**Comment by drbenmorgan** [comment]
Don't worry about it too much though for this or upcoming PRs - I've implemented Travis-CI for this repo, so the site is now built and tested automatically. If you add any further commits to this PR, then you'll get feedback on whether anything breaks.

**Comment by cherylepatrick** [comment]
That's clever! OK, I will not worry for what I have done now but try to use the feature branch workflow in future. Thanks Ben!

**Comment by drbenmorgan** [comment]
@cherylepatrick is there anything you want to add in the PR, or is it o.k. to merge this for publication?

**Comment by cherylepatrick** [comment]
Merge it! Yay!

**Pull request merged**
